stages:
  - compile
  - package
  - execute

job 1:
  stage: compile
  only:
    - master
  cache:
    paths:
      - target
  script:
    - mvn compile
  tags:
    - eacct_back_81

    
job 2:
  stage: package
  only:
    - master
  cache:
    paths:
      - target\*.jar
  script:
    - mvn package -DskipTests
  tags:
    - eacct_back_81


job 3:
  stage: execute
  only:
    - master
  cache:
    paths:
      - target
  script:
    - copy target\framework-0.0.1.jar d:\app\app.jar
  tags:
    - eacct_back_81

