stages:
  - Stop the service
  - Build
  - Copy
  - Start the service

job 1:
  stage: Stop the service
  only:
    - master
  script:
    - sudo systemctl stop etri-platform-api.service


job 2:
  stage: Build
  only:
    - master
  cache:
    paths:
      - build/*
  script:
    - gradle pathingJar
    - gradle bootJar

job 3:
  stage: Copy
  only:
    - master
  cache:
    paths:
      - build/*
  script:
    - sudo rm -rf /home/webdev/apps/etri-rs/platform-back/api.jar
    - sudo rm -rf /home/webdev/apps/etri-rf/platform-back/api-pathing.jar
    - sudo cp ./build/libs/api.jar /home/webdev/apps/etri-rs/platform-back/api.jar
    - sudo cp ./build/libs/api-pathing.jar /home/webdev/apps/etri-rs/platform-back/api-pathing.jar

job 4:
  stage: Start the service
  only:
    - master
  cache:
    paths:
      - build/*
  script:
    - sudo systemctl start etri-platform-api.service
