/* Menu */
CREATE TABLE A_MENU (
  COMP_CD varchar2(10) NOT NULL,
  MENU_NO varchar2(10) NOT NULL,
  MENU_NM varchar2(60),
  PROGRAM_FILE_NM varchar2(60),
  UPPER_MENU_NO varchar2(10),
  MENU_ORDR NUMBER(10, 0),
  MENU_DC varchar2(250),
  RELATE_IMAGE_PATH varchar2(100),
  RELATE_IMAGE_NM varchar2(60),
  CONSTRAINT PK_A_MENU PRIMARY KEY (COMP_CD,MENU_NO)
)
;
COMMENT ON TABLE A_MENU IS 'menu';

COMMENT ON COLUMN A_MENU.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_MENU.MENU_NO IS '메뉴순번';
COMMENT ON COLUMN A_MENU.MENU_NM IS '메뉴명';
COMMENT ON COLUMN A_MENU.PROGRAM_FILE_NM IS '프로그램명';
COMMENT ON COLUMN A_MENU.UPPER_MENU_NO IS '상위메뉴명';
COMMENT ON COLUMN A_MENU.MENU_ORDR IS '메뉴순서';
COMMENT ON COLUMN A_MENU.MENU_DC IS '메뉴설명';
COMMENT ON COLUMN A_MENU.RELATE_IMAGE_PATH IS '연결이미지경로';
COMMENT ON COLUMN A_MENU.RELATE_IMAGE_NM IS '연결이미지명';


/* Menu by Role */
CREATE TABLE A_MENU_ROLE (
  ROLE_CD varchar2(30) NOT NULL,
  MENU_NO varchar2(10) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  CONSTRAINT PK_A_MENU_ROLE PRIMARY KEY (COMP_CD,ROLE_CD,MENU_NO)
)
;
COMMENT ON TABLE A_MENU_ROLE IS 'menu_role';

COMMENT ON COLUMN A_MENU_ROLE.ROLE_CD IS '권한코드';
COMMENT ON COLUMN A_MENU_ROLE.MENU_NO IS '메뉴순번';
COMMENT ON COLUMN A_MENU_ROLE.COMP_CD IS '회사코드';


/* Role */
CREATE TABLE A_ROLE (
  COMP_CD varchar2(30) NOT NULL,
  ROLE_CD varchar2(30) NOT NULL,
  ROLE_NM varchar2(60) DEFAULT NULL,
  ROLE_SELECT_CD varchar2(30) DEFAULT NULL,
  ROLE_DC varchar2(200) DEFAULT NULL,
  CONSTRAINT PK_A_ROLE PRIMARY KEY (COMP_CD,ROLE_CD)
)
;
COMMENT ON TABLE A_ROLE IS 'role';

COMMENT ON COLUMN A_ROLE.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_ROLE.ROLE_CD IS '권한코드';
COMMENT ON COLUMN A_ROLE.ROLE_NM IS '권한명';
COMMENT ON COLUMN A_ROLE.ROLE_SELECT_CD IS '조회권한';
COMMENT ON COLUMN A_ROLE.ROLE_DC IS '권한설명';


/* Spring Session */
CREATE TABLE SPRING_SESSION (
  PRIMARY_ID varchar2(36) NOT NULL,
  SESSION_ID varchar2(36) NOT NULL,
  CREATION_TIME NUMBER(20, 0) NOT NULL,
  LAST_ACCESS_TIME NUMBER(20, 0) NOT NULL,
  MAX_INACTIVE_INTERVAL NUMBER(11, 0) NOT NULL,
  EXPIRY_TIME NUMBER(20, 0) NOT NULL,
  PRINCIPAL_NAME varchar2(100) DEFAULT NULL,
  CONSTRAINT PK_SPRING_SESSION PRIMARY KEY (PRIMARY_ID),
  CONSTRAINT UK_SPRING_SESSION_SESSION_ID UNIQUE (SESSION_ID)
)
;
CREATE INDEX SPRING_SESSION_INDEX ON SPRING_SESSION(PRIMARY_ID,SESSION_ID,EXPIRY_TIME,PRINCIPAL_NAME); 

/* Spring Session Attributes */
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID varchar2(36) NOT NULL,
  ATTRIBUTE_NAME varchar2(200) NOT NULL,
  ATTRIBUTE_BYTES blob NOT NULL,
  CONSTRAINT PK_SS_ATTRIBUTES PRIMARY KEY (SESSION_PRIMARY_ID,ATTRIBUTE_NAME),
  CONSTRAINT FK_SPRING_SESSION_ATTRIBUTES FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES spring_session (PRIMARY_ID) ON DELETE CASCADE
)
;


/* User */
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 MAXVALUE 10000 CYCLE NOCACHE;
CREATE TABLE A_USER (
  ID NUMBER(11, 0) NOT NULL,
  SESSION_P_ID varchar2(36) DEFAULT NULL,
  LOGIN_ID varchar2(30) DEFAULT NULL,
  LOGIN_PW varchar2(255) NOT NULL,
  COMP_CD varchar2(10) DEFAULT NULL,
  DEPT_CD varchar2(10) DEFAULT NULL,
  EMPLOYEE_NO varchar2(30) DEFAULT NULL,
  USER_NAME varchar2(80) DEFAULT NULL,
  ENABLE_FLAG NUMBER(3, 0) DEFAULT 1,
  ATTRIBUTE_1 varchar2(255) DEFAULT NULL,
  ATTRIBUTE_2 varchar2(30) DEFAULT NULL,
  ATTRIBUTE_3 varchar2(30) DEFAULT NULL,
  ATTRIBUTE_4 varchar2(30) DEFAULT NULL,
  ATTRIBUTE_5 varchar2(30) DEFAULT NULL,
  CREATED_BY NUMBER(11, 0) DEFAULT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  MODIFIED_BY NUMBER(11, 0) DEFAULT NULL,
  MODIFIED_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT PK_A_USER PRIMARY KEY (id),
  CONSTRAINT UK_A_USER_LOGIN_ID UNIQUE (LOGIN_ID),
  CONSTRAINT A_USER_FK1 FOREIGN KEY (CREATED_BY) REFERENCES A_USER (id),
  CONSTRAINT A_USER_FK2 FOREIGN KEY (MODIFIED_BY) REFERENCES A_USER (id),
  CONSTRAINT A_USER_FK3 FOREIGN KEY (SESSION_P_ID) REFERENCES SPRING_SESSION (PRIMARY_ID)
)
;
COMMENT ON TABLE A_USER IS 'user';

COMMENT ON COLUMN A_USER.LOGIN_ID IS '로그인ID_사번';
COMMENT ON COLUMN A_USER.LOGIN_PW IS '로그인PW';
COMMENT ON COLUMN A_USER.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_USER.DEPT_CD IS '부서코드';
COMMENT ON COLUMN A_USER.EMPLOYEE_NO IS 'employee no';
COMMENT ON COLUMN A_USER.USER_NAME IS '사용자명';
COMMENT ON COLUMN A_USER.ENABLE_FLAG IS '사용유무';
COMMENT ON COLUMN A_USER.CREATED_BY IS '생성자';
COMMENT ON COLUMN A_USER.CREATION_DATE IS '생성일시';
COMMENT ON COLUMN A_USER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN A_USER.MODIFIED_DATE IS '수정일시';


/* USER Personal Menu */
CREATE TABLE A_USER_MENU (
  USER_ID varchar2(10) NOT NULL,
  MENU_NO varchar2(10) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  MENU_ORDR NUMBER(10, 0) DEFAULT NULL,
  MENU_ICON_CD varchar2(30) DEFAULT NULL,
  CONSTRAINT PK_A_USER_MENU PRIMARY KEY (COMP_CD,USER_ID,MENU_NO)
)
;
COMMENT ON TABLE A_USER_MENU IS 'user menu';

COMMENT ON COLUMN A_USER_MENU.USER_ID IS '사원번호';
COMMENT ON COLUMN A_USER_MENU.MENU_NO IS '메뉴순번';
COMMENT ON COLUMN A_USER_MENU.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_USER_MENU.MENU_ORDR IS '메뉴순서';
COMMENT ON COLUMN A_USER_MENU.MENU_ICON_CD IS '메뉴아이콘코드';


/* USER ROLE */
CREATE TABLE A_USER_ROLE (
  ID NUMBER(11, 0) NOT NULL,
  USER_ID NUMBER(11, 0) DEFAULT NULL,
  COMP_CD varchar2(10) NOT NULL,
  ROLE varchar2(30) NOT NULL,
  CREATED_BY NUMBER(11, 0) DEFAULT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  MODIFIED_BY NUMBER(11, 0) DEFAULT NULL,
  MODIFIED_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT PK_A_USER_ROLE PRIMARY KEY (id,comp_cd),
  CONSTRAINT A_USER_ROLE_FK FOREIGN KEY (USER_ID) REFERENCES A_USER (id)
)
;
COMMENT ON TABLE A_USER_ROLE IS 'User role';

COMMENT ON COLUMN A_USER_ROLE.ID IS 'ID';
COMMENT ON COLUMN A_USER_ROLE.USER_ID IS 'A_USER.ID';
COMMENT ON COLUMN A_USER_ROLE.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_USER_ROLE.ROLE IS '권한';
COMMENT ON COLUMN A_USER_ROLE.CREATED_BY IS '생성자';
COMMENT ON COLUMN A_USER_ROLE.CREATION_DATE IS '생성일시';
COMMENT ON COLUMN A_USER_ROLE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN A_USER_ROLE.MODIFIED_DATE IS '수정일시';


/* OAUTH2.0 */
CREATE SEQUENCE oauth_seq START WITH 1 INCREMENT BY 1 MAXVALUE 10000 CYCLE NOCACHE;
CREATE TABLE A_OAUTH (
  ID NUMBER(11, 0) NOT NULL,
  EMP_NO varchar2(100) NOT NULL,
  EMAIL varchar2(100) NOT NULL,
  NAME varchar2(100) DEFAULT NULL,
  PICTURE varchar2(100) DEFAULT NULL,
  TYPE varchar2(100) DEFAULT NULL,
  CREATE_DATE date DEFAULT NULL,
  MODIFIED_DATE date DEFAULT NULL,
  CONSTRAINT PK_A_OAUTH PRIMARY KEY (id)
)
;

/* File */
CREATE SEQUENCE file_seq START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 CYCLE NOCACHE;
CREATE TABLE A_FILE (
  ID NUMBER(11, 0) NOT NULL,
  COMP_CD varchar2(10) DEFAULT NULL,
  FILE_TYPE varchar2(30) DEFAULT NULL,
  DOCUMENT_H_ID varchar2(20) DEFAULT NULL,
  REMARK varchar2(255) DEFAULT NULL,
  SEQ NUMBER(11, 0) DEFAULT NULL,
  ORIGINAL_NAME varchar2(255) NOT NULL,
  STORED_NAME varchar2(255) NOT NULL,
  DOWNLOAD_URL varchar2(255) NOT NULL,
  FILE_CAT varchar2(30) DEFAULT NULL,
  FILE_SIZE NUMBER(11, 0) DEFAULT NULL,
  ATTRIBUTE_1 varchar2(255) DEFAULT NULL,
  ATTRIBUTE_2 varchar2(255) DEFAULT NULL,
  ATTRIBUTE_3 varchar2(255) DEFAULT NULL,
  ATTRIBUTE_4 varchar2(255) DEFAULT NULL,
  ATTRIBUTE_5 varchar2(255) DEFAULT NULL,
  CREATED_BY NUMBER(11, 0) DEFAULT NULL,
  CREATION_DATE date DEFAULT SYSDATE,
  MODIFIED_BY NUMBER(11, 0) DEFAULT NULL,
  MODIFIED_DATE date DEFAULT SYSDATE,
  CONSTRAINT PK_A_FILE PRIMARY KEY (ID),
  CONSTRAINT UK_A_FILE_STORED_NAME UNIQUE (STORED_NAME)
)
;
CREATE INDEX A_FILE_INDEX ON A_FILE(DOCUMENT_H_ID,created_by,modified_by); 

COMMENT ON TABLE A_FILE IS 'File';

COMMENT ON COLUMN A_FILE.ID IS 'ID';
COMMENT ON COLUMN A_FILE.COMP_CD IS '회사코드';
COMMENT ON COLUMN A_FILE.FILE_TYPE IS '관리구분(예시:모바일,전표,예산)';
COMMENT ON COLUMN A_FILE.DOCUMENT_H_ID IS '문서관리번호(예시:전표,예산)';
COMMENT ON COLUMN A_FILE.REMARK IS '파일설명';
COMMENT ON COLUMN A_FILE.SEQ IS '파일순서';
COMMENT ON COLUMN A_FILE.ORIGINAL_NAME IS '원본파일명';
COMMENT ON COLUMN A_FILE.STORED_NAME IS '저장파일명';
COMMENT ON COLUMN A_FILE.DOWNLOAD_URL IS '다운로드 URL';
COMMENT ON COLUMN A_FILE.FILE_CAT IS '파일경로';
COMMENT ON COLUMN A_FILE.FILE_SIZE IS '용량(Byte)';
COMMENT ON COLUMN A_FILE.ATTRIBUTE_1 IS '썸네일_저장파일명';
COMMENT ON COLUMN A_FILE.ATTRIBUTE_2 IS '썸네일_파일경로';
COMMENT ON COLUMN A_FILE.ATTRIBUTE_3 IS '원본 관리구분(모바일)';
COMMENT ON COLUMN A_FILE.ATTRIBUTE_4 IS '비고4';
COMMENT ON COLUMN A_FILE.ATTRIBUTE_5 IS '비고5';
COMMENT ON COLUMN A_FILE.CREATED_BY IS '생성자';
COMMENT ON COLUMN A_FILE.CREATION_DATE IS '생성일시';
COMMENT ON COLUMN A_FILE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN A_FILE.MODIFIED_DATE IS '수정일시';

/* Employee */
CREATE TABLE TB_MST_EMP (
  EMP_NO varchar2(10) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  EMP_NM varchar2(50) DEFAULT NULL,
  COMP_NM varchar2(100) DEFAULT NULL,
  DEPT_CD varchar2(10) DEFAULT NULL,
  DEPT_NM varchar2(100) DEFAULT NULL,
  CCTR_CD varchar2(10) DEFAULT NULL,
  CCTR_NM varchar2(100) DEFAULT NULL,
  BP_CD varchar2(10) DEFAULT NULL,
  BP_NM varchar2(100) DEFAULT NULL,
  UPPER_DEPT_CD varchar2(10) DEFAULT NULL,
  UPPER_DEPT_NM varchar2(100) DEFAULT NULL,
  EMP_DV_CD varchar2(10) DEFAULT NULL,
  EMP_DV_NM varchar2(100) DEFAULT NULL,
  JOB_GROUP_CD varchar2(10) DEFAULT NULL,
  JOB_GROUP_NM varchar2(100) DEFAULT NULL,
  JOB_DUT_CD varchar2(10) DEFAULT NULL,
  JOB_DUT_NM varchar2(100) DEFAULT NULL,
  JOB_GRADE_CD varchar2(10) DEFAULT NULL,
  JOB_GRADE_NM varchar2(100) DEFAULT NULL,
  JOB_CD varchar2(20) DEFAULT NULL,
  JOB_NM varchar2(100) DEFAULT NULL,
  TITLE_CD varchar2(10) DEFAULT NULL,
  TITLE_NM varchar2(100) DEFAULT NULL,
  SERVE_CD varchar2(2) DEFAULT NULL,
  SERVE_NM varchar2(100) DEFAULT NULL,
  HIRE_CD varchar2(2) DEFAULT NULL,
  HIRE_NM varchar2(100) DEFAULT NULL,
  GRP_JOIN_DT varchar2(8) DEFAULT NULL,
  JOIN_DT varchar2(8) DEFAULT NULL,
  RETIRE_DT varchar2(8) DEFAULT NULL,
  EMAIL varchar2(224) DEFAULT NULL,
  OFF_TEL_NO varchar2(64) DEFAULT NULL,
  MOB_TEL_NO varchar2(64) DEFAULT NULL,
  VEND_CD varchar2(10) DEFAULT NULL,
  PICODE varchar2(20) DEFAULT NULL,
  PISTAT varchar2(1) DEFAULT NULL,
  PIDATE varchar2(8) DEFAULT NULL,
  PITIME varchar2(6) DEFAULT NULL,
  PIUSER varchar2(20) DEFAULT NULL,
  PIMSG varchar2(400) DEFAULT NULL,
  PIMSGID varchar2(32) DEFAULT NULL,
  CONSTRAINT PK_TB_MST_EMP PRIMARY KEY (EMP_NO,COMP_CD)
)
;
COMMENT ON TABLE TB_MST_EMP IS 'Employee';

COMMENT ON COLUMN TB_MST_EMP.EMP_NO IS '사원번호';
COMMENT ON COLUMN TB_MST_EMP.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_MST_EMP.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_MST_EMP.CCTR_CD IS '비용부서코드';
COMMENT ON COLUMN TB_MST_EMP.BP_CD IS '사업장코드';
COMMENT ON COLUMN TB_MST_EMP.UPPER_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN TB_MST_EMP.EMP_DV_CD IS '사원구분코드';
COMMENT ON COLUMN TB_MST_EMP.JOB_GROUP_CD IS '직군코드';
COMMENT ON COLUMN TB_MST_EMP.JOB_DUT_CD IS '직책코드';
COMMENT ON COLUMN TB_MST_EMP.JOB_GRADE_CD IS '직급코드';
COMMENT ON COLUMN TB_MST_EMP.JOB_CD IS '직무코드';
COMMENT ON COLUMN TB_MST_EMP.TITLE_CD IS '호칭코드';
COMMENT ON COLUMN TB_MST_EMP.SERVE_CD IS '재직상태코드(10:재직, 20:휴직, 30:퇴직)';
COMMENT ON COLUMN TB_MST_EMP.HIRE_CD IS '채용구분코드';
COMMENT ON COLUMN TB_MST_EMP.GRP_JOIN_DT IS '그룹입사일자';
COMMENT ON COLUMN TB_MST_EMP.JOIN_DT IS '입사일자';
COMMENT ON COLUMN TB_MST_EMP.RETIRE_DT IS '퇴사일자';
COMMENT ON COLUMN TB_MST_EMP.EMAIL IS '이메일';
COMMENT ON COLUMN TB_MST_EMP.OFF_TEL_NO IS '사무실전화번호';
COMMENT ON COLUMN TB_MST_EMP.MOB_TEL_NO IS '모바일전화번호';
COMMENT ON COLUMN TB_MST_EMP.VEND_CD IS '거래처코드';
COMMENT ON COLUMN TB_MST_EMP.PICODE IS 'I/F ID';
COMMENT ON COLUMN TB_MST_EMP.PISTAT IS 'I/F 상태';
COMMENT ON COLUMN TB_MST_EMP.PIDATE IS 'I/F 일자';
COMMENT ON COLUMN TB_MST_EMP.PITIME IS 'I/F 시간';
COMMENT ON COLUMN TB_MST_EMP.PIUSER IS 'I/F 유저';
COMMENT ON COLUMN TB_MST_EMP.PIMSG IS '전송메시지';
COMMENT ON COLUMN TB_MST_EMP.PIMSGID IS '메시지ID';

/* Department */
CREATE TABLE TB_MST_DEPT (
  COMP_CD varchar2(10) NOT NULL,
  DEPT_NO varchar2(10) DEFAULT NULL,
  DEPT_NAME varchar2(100) DEFAULT NULL,
  ADMR_DEPT_NO varchar2(10) DEFAULT NULL,
  LOCATION varchar2(50) DEFAULT NULL,
  CONSTRAINT PK_TB_MST_DEPT PRIMARY KEY (COMP_CD,DEPT_NO)
)
;
COMMENT ON TABLE TB_MST_DEPT IS 'Department';

COMMENT ON COLUMN TB_MST_EMP.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_MST_EMP.DEPT_NO IS '부서번호';
COMMENT ON COLUMN TB_MST_EMP.DEPT_NAME IS '부서이름';
COMMENT ON COLUMN TB_MST_EMP.ADMR_DEPT_NO IS '관리부서(상위부서)';
COMMENT ON COLUMN TB_MST_EMP.LOCATION IS '위치';

/* Login History */
CREATE SEQUENCE login_history_seq START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 CYCLE NOCACHE;
CREATE TABLE TB_USER_LOGIN_HISTORY (
  LOG_ID NUMBER(11, 0) NOT NULL,
  CONNECT_ID varchar2(30) DEFAULT NULL,
  CONNECT_IP varchar2(30) DEFAULT NULL,
  CONNECT_MTHD varchar2(30) DEFAULT NULL,
  CONNECT_ERROR varchar2(100) DEFAULT NULL,
  CONNECT_URL varchar2(100) DEFAULT SYSDATE,
  CREATION_DATE date DEFAULT NULL,
  CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY (log_id)
)
;
COMMENT ON TABLE TB_USER_LOGIN_HISTORY IS 'LoginHistory';

COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.LOG_ID IS '고유ID';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CONNECT_ID IS '접속ID';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CONNECT_IP IS '접속IP';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CONNECT_MTHD IS '접속방법(W/M) - Web/Mobile';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CONNECT_ERROR IS '접속오류메시지';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CONNECT_URL IS '접속URL';
COMMENT ON COLUMN TB_USER_LOGIN_HISTORY.CREATION_DATE IS '접속일시';

/* ================================================================================================================== */

/* 기준코드 Header */
CREATE TABLE TB_CODE_HD (
  GROUP_CD varchar2(30) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  GROUP_NM varchar2(100) DEFAULT NULL,
  GROUP_DESC varchar2(200) DEFAULT NULL,
  USE_YN varchar2(1) DEFAULT NULL,
  REMARK varchar2(200) DEFAULT NULL,
  REG_ID varchar2(20) DEFAULT NULL,
  REG_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) DEFAULT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_CODE_HD PRIMARY KEY (GROUP_CD,COMP_CD)
)
;
COMMENT ON TABLE TB_CODE_HD IS '공통코드_헤더';

COMMENT ON COLUMN TB_CODE_HD.GROUP_CD IS '그룹코드';
COMMENT ON COLUMN TB_CODE_HD.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_CODE_HD.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_CODE_HD.REMARK IS '비고';


/* 기준코드 Detail */
CREATE TABLE TB_CODE_DT (
  GROUP_CD varchar2(30) NOT NULL,
  DETAIL_CD varchar2(30) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  DETAIL_NM varchar2(100) DEFAULT NULL,
  USE_YN varchar2(1) DEFAULT NULL,
  ORDER_SEQ NUMBER(11, 0) DEFAULT NULL,
  DETAIL_DESC varchar2(1000) DEFAULT NULL,
  REMARK1 varchar2(200) DEFAULT NULL,
  REMARK2 varchar2(200) DEFAULT NULL,
  REMARK3 varchar2(200) DEFAULT NULL,
  REMARK4 varchar2(200) DEFAULT NULL,
  REMARK5 varchar2(200) DEFAULT NULL,
  REG_ID varchar2(20) DEFAULT NULL,
  REG_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) DEFAULT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_CODE_DT PRIMARY KEY (GROUP_CD,DETAIL_CD,COMP_CD)
)
;
COMMENT ON TABLE TB_CODE_DT IS '공통코드_상세';

COMMENT ON COLUMN TB_CODE_DT.GROUP_CD IS '그룹코드';
COMMENT ON COLUMN TB_CODE_DT.DETAIL_CD IS '상세코드';
COMMENT ON COLUMN TB_CODE_DT.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_CODE_DT.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_CODE_DT.ORDER_SEQ IS '정렬순서';
COMMENT ON COLUMN TB_CODE_DT.DETAIL_DESC IS '설명';
COMMENT ON COLUMN TB_CODE_DT.REMARK1 IS '비고1';


/* 결재 헤더 */
CREATE TABLE TB_APPR_HD (
  APPR_NO varchar2(30) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  DOC_TYPE_CD varchar2(10) DEFAULT NULL,
  DOC_MNG_NO varchar2(30) DEFAULT NULL,
  DOC_TITLE_NM varchar2(100) DEFAULT NULL,
  DOC_STAT_CD varchar2(10) DEFAULT NULL,
  DRAFT_ID varchar2(20) DEFAULT NULL,
  DRAFT_DTM date DEFAULT SYSDATE,
  FNL_SEQ NUMBER(6, 0) DEFAULT NULL,
  REMARK varchar2(100) DEFAULT NULL,
  DOC_IN_VAL varchar2(20) DEFAULT NULL,
  REG_ID varchar2(20) DEFAULT NULL,
  REG_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) DEFAULT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_APPR_HD PRIMARY KEY (APPR_NO)
)
;
COMMENT ON TABLE TB_APPR_HD IS '결재_헤더';

COMMENT ON COLUMN TB_APPR_HD.APPR_NO IS '결재번호';
COMMENT ON COLUMN TB_APPR_HD.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_APPR_HD.DOC_TYPE_CD IS '문서유형코드';
COMMENT ON COLUMN TB_APPR_HD.DOC_MNG_NO IS '문서관리번호';
COMMENT ON COLUMN TB_APPR_HD.DOC_TITLE_NM IS '문서제목';
COMMENT ON COLUMN TB_APPR_HD.DOC_STAT_CD IS '문서상태코드';
COMMENT ON COLUMN TB_APPR_HD.DRAFT_ID IS '기안자ID';
COMMENT ON COLUMN TB_APPR_HD.DRAFT_DTM IS '기안일시';
COMMENT ON COLUMN TB_APPR_HD.FNL_SEQ IS '최종순번';
COMMENT ON COLUMN TB_APPR_HD.REMARK IS '비고';
COMMENT ON COLUMN TB_APPR_HD.DOC_IN_VAL IS '문서고유번호';


/* 결재 상세 */
CREATE TABLE TB_APPR_DT (
  APPR_NO varchar2(30) NOT NULL,
  APPR_SEQ NUMBER(6, 0) NOT NULL,
  COMP_CD varchar2(10) NOT NULL,
  APPR_TYPE_CD varchar2(10) DEFAULT NULL,
  APPR_FG_CD varchar2(10) DEFAULT NULL,
  APRVER_ID varchar2(20) DEFAULT NULL,
  APRVER_NM varchar2(100) DEFAULT NULL,
  APRVER_DEPT_NM varchar2(200) DEFAULT NULL,
  APRVER_JOB_NM varchar2(100) DEFAULT NULL,
  FIX_YN varchar2(1) DEFAULT NULL,
  A_APRVER_ID varchar2(20) DEFAULT NULL,
  A_APRVER_NM varchar2(100) DEFAULT NULL,
  A_APRVER_DEPT_NM varchar2(200) DEFAULT NULL,
  A_APRVER_JOB_NM varchar2(100) DEFAULT NULL,
  APPR_DTM date DEFAULT NULL,
  APPR_DESC varchar2(200) DEFAULT NULL,
  REMARK varchar2(400) DEFAULT NULL,
  REG_ID varchar2(20) DEFAULT NULL,
  REG_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) DEFAULT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_APPR_DT PRIMARY KEY (APPR_NO,APPR_SEQ)
)
;
COMMENT ON TABLE TB_APPR_DT IS '결재라인';

COMMENT ON COLUMN TB_APPR_DT.APPR_NO IS '결재번호';
COMMENT ON COLUMN TB_APPR_DT.APPR_SEQ IS '결재순번';
COMMENT ON COLUMN TB_APPR_DT.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_APPR_DT.APPR_TYPE_CD IS '결재유형코드';
COMMENT ON COLUMN TB_APPR_DT.APPR_FG_CD IS '결재구분코드';
COMMENT ON COLUMN TB_APPR_DT.APRVER_ID IS '결재자사번';
COMMENT ON COLUMN TB_APPR_DT.APRVER_DEPT_NM IS '결재자부서명';
COMMENT ON COLUMN TB_APPR_DT.APRVER_JOB_NM IS '결재자직급명';
COMMENT ON COLUMN TB_APPR_DT.FIX_YN IS '고정결재여부';
COMMENT ON COLUMN TB_APPR_DT.A_APRVER_ID IS '실결재자ID';
COMMENT ON COLUMN TB_APPR_DT.A_APRVER_DEPT_NM IS '실결재자부서명';
COMMENT ON COLUMN TB_APPR_DT.A_APRVER_JOB_NM IS '실결재자부서명';
COMMENT ON COLUMN TB_APPR_DT.APPR_DTM IS '결재일시';
COMMENT ON COLUMN TB_APPR_DT.APPR_DESC IS '결재의견';
COMMENT ON COLUMN TB_APPR_DT.REMARK IS '비고';


/* 전결규정 */
CREATE TABLE TB_APPR_RULE (
  COMP_CD varchar2(10) NOT NULL,
  DOC_TYPE_CD varchar2(10) NOT NULL,
  DTL_TYPE_CD varchar2(10) NOT NULL,
  CUR_CD varchar2(10) NOT NULL,
  RULE_SEQ NUMBER(6, 0) NOT NULL,
  USE_YN varchar2(1) DEFAULT NULL,
  MAX_AMT decimal(15,0) DEFAULT NULL,
  APPR_TYPE_CD varchar2(10) DEFAULT NULL,
  FIX_YN varchar2(1) DEFAULT NULL,
  APRVER_CLASS_CD varchar2(10) DEFAULT NULL,
  APRVER_CLASS_VAL varchar2(20) DEFAULT NULL,
  REMARK varchar2(100) DEFAULT NULL,
  REG_ID varchar2(20) NOT NULL,
  REGI_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) NOT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_APPR_RULE PRIMARY KEY (COMP_CD,DOC_TYPE_CD,DTL_TYPE_CD,CUR_CD,RULE_SEQ)
)
;
COMMENT ON TABLE TB_APPR_RULE IS '전결규정';

COMMENT ON COLUMN TB_APPR_RULE.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_APPR_RULE.DOC_TYPE_CD IS '문서유형코드';
COMMENT ON COLUMN TB_APPR_RULE.DTL_TYPE_CD IS '상세유형코드';
COMMENT ON COLUMN TB_APPR_RULE.CUR_CD IS '통화코드';
COMMENT ON COLUMN TB_APPR_RULE.RULE_SEQ IS '순번';
COMMENT ON COLUMN TB_APPR_RULE.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_APPR_RULE.MAX_AMT IS '상한금액';
COMMENT ON COLUMN TB_APPR_RULE.APPR_TYPE_CD IS '결재유형코드';
COMMENT ON COLUMN TB_APPR_RULE.FIX_YN IS '고정결재여부';
COMMENT ON COLUMN TB_APPR_RULE.APRVER_CLASS_CD IS '결재자분류코드';
COMMENT ON COLUMN TB_APPR_RULE.APRVER_CLASS_VAL IS '결재자분류값';
COMMENT ON COLUMN TB_APPR_RULE.REMARK IS '비고';


/* 결재 위임 */
CREATE TABLE TB_APPR_DELEGATE(
  ADLG_ID varchar2(20) NOT NULL,
  ACT_ID varchar2(20) NOT NULL,
  ADLG_SEQ NUMBER(6, 0) NOT NULL,
  COMP_CD varchar2(10) DEFAULT NULL,
  ADLG_STAT_CD varchar2(10) DEFAULT NULL,
  ADLG_STR_DT varchar2(8) DEFAULT NULL,
  ADLG_END_DT varchar2(8) DEFAULT NULL,
  ADLG_RSN varchar2(200) DEFAULT NULL,
  ADLG_EXE_DTM date DEFAULT NULL,
  ADLG_RVC_DTM date DEFAULT NULL,
  REG_ID varchar2(20) DEFAULT NULL,
  REG_DTM date DEFAULT SYSDATE,
  CHG_ID varchar2(20) DEFAULT NULL,
  CHG_DTM date DEFAULT SYSDATE,
  CONSTRAINT PK_TB_APPR_DELEGATE PRIMARY KEY (ADLG_ID,ACT_ID,ADLG_SEQ)
)
;
COMMENT ON TABLE TB_APPR_DELEGATE IS '결재위임';

COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_ID IS '위임자ID';
COMMENT ON COLUMN TB_APPR_DELEGATE.ACT_ID IS '수임자ID';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_SEQ IS '순번';
COMMENT ON COLUMN TB_APPR_DELEGATE.COMP_CD IS '회사코드';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_STAT_CD IS '위임상태코드';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_STR_DT IS '위임시작일자';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_END_DT IS '위임종료일자';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_RSN IS '위임사유내용';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_EXE_DTM IS '위임실행일시';
COMMENT ON COLUMN TB_APPR_DELEGATE.ADLG_RVC_DTM IS '위임해제일시';
